services:
  backend:
    build: ./backend
    container_name: monitor_ipu_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
      
    networks:
      - minha_rede

    depends_on:
      postgres:
        condition: service_healthy
     
  postgres:
    image: postgres:16
    container_name: monitor_ipu_db
    restart: unless-stopped
    ports:
      - "25432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d monitor_ipu_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  
networks:
  minha_rede:
    driver: bridge
